/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_hkwindowgestion (void);
GtkWidget* create_hkwindowajouter (void);
GtkWidget* create_hkwindowmodifier (void);
GtkWidget* create_hkwindowtache2 (void);
GtkWidget* create_hkwindowmail (void);
GtkWidget* create_hkwindowsupp (void);
GtkWidget* create_window1_gestion (void);
GtkWidget* create_window2_liste (void);
GtkWidget* create_window3_supp (void);
GtkWidget* create_window4_ajout (void);
GtkWidget* create_window5_modif (void);
GtkWidget* create_window6_hors_norme (void);
GtkWidget* create_hh_window_produits (void);
GtkWidget* create_hh_window_supp (void);
GtkWidget* create_hh_window_ajout (void);
GtkWidget* create_hh_window_modif (void);
GtkWidget* create_hh_window_Rechercher (void);
GtkWidget* create_hh_window_rupture (void);
GtkWidget* create_hh_mail (void);
GtkWidget* create_RE_window1_gestion (void);
GtkWidget* create_RE_window2_liste (void);
GtkWidget* create_RE_window3_supp (void);
GtkWidget* create_RE_window4_ajout (void);
GtkWidget* create_RE_window5_modif (void);
GtkWidget* create_RE_dash (void);
GtkWidget* create_FB_window1 (void);
GtkWidget* create_FB_window2 (void);
GtkWidget* create_FB_window3 (void);
GtkWidget* create_FB_window4 (void);
GtkWidget* create_FB_window5 (void);
GtkWidget* create_FB_window6 (void);
GtkWidget* create_MNaccueil (void);
GtkWidget* create_MNajout (void);
GtkWidget* create_MNmodif (void);
GtkWidget* create_MNsupprime (void);
GtkWidget* create_MNcherche (void);
GtkWidget* create_MNetagepanne (void);
GtkWidget* create_MNauthentification (void);
GtkWidget* create_MNmenu (void);
GtkWidget* create_dashboard_window_int (void);
